#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'FYPopupController_Example' do
  pod 'FYPopupController', :path => '../'

  target 'FYPopupController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    #pod 'Masonry'
  end
end
